version: '2'

networks:
  app-tier:
    driver: bridge

services:
  elasticsearch-master-0:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-master-0
    environment:
      ELASTICSEARCH_IS_DEDICATED_NODE:      yes
      ELASTICSEARCH_NODE_ROLES:             master
      ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
      ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
      ELASTICSEARCH_CLUSTER_NAME:           elastic
      ELASTICSEARCH_CLUSTER_HOSTS:         elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
      ELASTICSEARCH_TOTAL_NODES:            4
      ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
      ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
      ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-master-0
      ELASTICSEARCH_HEAP_SIZE:              1024m
      ELASTICSEARCH_ENABLE_SECURITY:        true
      ELASTICSEARCH_PASSWORD:               Elastic123
      ELASTICSEARCH_ENABLE_FIPS_MODE:       false
      ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      ELASTICSEARCH_ENABLE_REST_TLS:        true
      ELASTICSEARCH_TLS_USE_PEM:            true
      LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-master.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-master.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt
       - data-elasticsearch-master-0:/bitnami/elasticsearch/data
    networks:
      - app-tier
      
      
  elasticsearch-master-1:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-master-1
    environment:
      ELASTICSEARCH_IS_DEDICATED_NODE:      yes
      ELASTICSEARCH_NODE_ROLES:             master
      ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
      ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
      ELASTICSEARCH_CLUSTER_NAME:           elastic
      ELASTICSEARCH_CLUSTER_HOSTS:          elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
      ELASTICSEARCH_TOTAL_NODES:            4
      ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
      ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
      ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-master-1
      ELASTICSEARCH_HEAP_SIZE:              1024m
      ELASTICSEARCH_ENABLE_SECURITY:        true
      ELASTICSEARCH_PASSWORD:               Elastic123
      ELASTICSEARCH_ENABLE_FIPS_MODE:       false
      ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      ELASTICSEARCH_ENABLE_REST_TLS:        true
      ELASTICSEARCH_TLS_USE_PEM:            true
      LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-master.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-master.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
       - data-elasticsearch-master-1:/bitnami/elasticsearch/data
    networks:
      - app-tier


  elasticsearch-data-0:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-data-0
    environment:
        BITNAMI_DEBUG:                        false
        MY_POD_NAME:                          elasticsearch-data-0 
        ELASTICSEARCH_IS_DEDICATED_NODE:      yes
        ELASTICSEARCH_NODE_ROLES:             data
        ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
        ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
        ELASTICSEARCH_CLUSTER_NAME:           elastic
        ELASTICSEARCH_CLUSTER_HOSTS: elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
        ELASTICSEARCH_TOTAL_NODES:            4
        ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
        ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
        ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-data-0
        ELASTICSEARCH_HEAP_SIZE:              1024m
        ELASTICSEARCH_ENABLE_SECURITY:        true
        ELASTICSEARCH_PASSWORD:               Elastic123
        ELASTICSEARCH_ENABLE_FIPS_MODE:       false
        ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
        ELASTICSEARCH_ENABLE_REST_TLS:        true
        ELASTICSEARCH_TLS_USE_PEM:            true
        LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-data.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-data.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
       - data-elasticsearch-data-0:/bitnami/elasticsearch/data
    networks:
      - app-tier
      
      
      
  elasticsearch-data-1:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-data-1
    environment:
        BITNAMI_DEBUG:                        false
        MY_POD_NAME:                          elasticsearch-data-1 
        ELASTICSEARCH_IS_DEDICATED_NODE:      yes
        ELASTICSEARCH_NODE_ROLES:             data
        ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
        ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
        ELASTICSEARCH_CLUSTER_NAME:           elastic
        ELASTICSEARCH_CLUSTER_HOSTS:          elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
        ELASTICSEARCH_TOTAL_NODES:            4
        ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
        ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
        ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-data-1 
        ELASTICSEARCH_HEAP_SIZE:              1024m
        ELASTICSEARCH_ENABLE_SECURITY:        true
        ELASTICSEARCH_PASSWORD:               Elastic123
        ELASTICSEARCH_ENABLE_FIPS_MODE:       false
        ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
        ELASTICSEARCH_ENABLE_REST_TLS:        true
        ELASTICSEARCH_TLS_USE_PEM:            true
        LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-data.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-data.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
       - data-elasticsearch-data-1:/bitnami/elasticsearch/data
    networks:
      - app-tier


  elasticsearch-ingest-0:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-ingest-0
    environment:
      BITNAMI_DEBUG:                        false
      MY_POD_NAME:                          elasticsearch-ingest-0 
      ELASTICSEARCH_IS_DEDICATED_NODE:      yes
      ELASTICSEARCH_NODE_ROLES:             ingest
      ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
      ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
      ELASTICSEARCH_CLUSTER_NAME:           elastic
      ELASTICSEARCH_CLUSTER_HOSTS:          elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
      ELASTICSEARCH_TOTAL_NODES:            4
      ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
      ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
      ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-ingest-0 
      ELASTICSEARCH_HEAP_SIZE:              1024m
      ELASTICSEARCH_ENABLE_SECURITY:        true
      ELASTICSEARCH_PASSWORD:               Elastic123
      ELASTICSEARCH_ENABLE_FIPS_MODE:       false
      ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      ELASTICSEARCH_ENABLE_REST_TLS:        true
      ELASTICSEARCH_TLS_USE_PEM:            true
      LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-ingest.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-ingest.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
#      - data-elasticsearch-ingest-0:/bitnami/elasticsearch/data
    networks:
      - app-tier

  elasticsearch-ingest-1:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-ingest-1
    environment:
      BITNAMI_DEBUG:                        false
      MY_POD_NAME:                          elasticsearch-ingest-1 
      ELASTICSEARCH_IS_DEDICATED_NODE:      yes
      ELASTICSEARCH_NODE_ROLES:             ingest
      ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
      ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
      ELASTICSEARCH_CLUSTER_NAME:           elastic
      ELASTICSEARCH_CLUSTER_HOSTS:          elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
      ELASTICSEARCH_TOTAL_NODES:            4
      ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
      ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
      ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-ingest-1 
      ELASTICSEARCH_HEAP_SIZE:              1024m
      ELASTICSEARCH_ENABLE_SECURITY:        true
      ELASTICSEARCH_PASSWORD:               Elastic123
      ELASTICSEARCH_ENABLE_FIPS_MODE:       false
      ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      ELASTICSEARCH_ENABLE_REST_TLS:        true
      ELASTICSEARCH_TLS_USE_PEM:            true
      LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-ingest.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-ingest.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
#      - data-elasticsearch-ingest-1:/bitnami/elasticsearch/data
    networks:
      - app-tier

  elasticsearch-coordinating-0:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-coordinating-0
    environment:
      MY_POD_NAME:                          elasticsearch-coordinating-0 
      BITNAMI_DEBUG:                        false
      ELASTICSEARCH_CLUSTER_NAME:           elastic
      ELASTICSEARCH_IS_DEDICATED_NODE:      yes
      ELASTICSEARCH_NODE_ROLES:
      ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
      ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
      ELASTICSEARCH_CLUSTER_HOSTS:          elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
      ELASTICSEARCH_TOTAL_NODES:            4
      ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
      ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
      ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-coordinating-0
      ELASTICSEARCH_HEAP_SIZE:              1024m
      ELASTICSEARCH_ENABLE_SECURITY:        true
      ELASTICSEARCH_PASSWORD:               Elastic123
      ELASTICSEARCH_ENABLE_FIPS_MODE:       false
      ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      ELASTICSEARCH_ENABLE_REST_TLS:        true
      ELASTICSEARCH_TLS_USE_PEM:            true
      LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-coordinating.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-coordinating.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
#      - data-elasticsearch-coordinating-1:/bitnami/elasticsearch/data
    networks:
      - app-tier

  elasticsearch-coordinating-1:
    image: 'bitnami/elasticsearch:latest'
    hostname: elasticsearch-coordinating-1
    environment:
      MY_POD_NAME:                          elasticsearch-coordinating-1 
      BITNAMI_DEBUG:                        false
      ELASTICSEARCH_CLUSTER_NAME:           elastic
      ELASTICSEARCH_IS_DEDICATED_NODE:      yes
      ELASTICSEARCH_NODE_ROLES:
      ELASTICSEARCH_TRANSPORT_PORT_NUMBER:  9300
      ELASTICSEARCH_HTTP_PORT_NUMBER:       9200
      ELASTICSEARCH_CLUSTER_HOSTS:          elasticsearch-master-0,elasticsearch-master-1,elasticsearch-coordinating-0,elasticsearch-coordinating-1,elasticsearch-data-0,elasticsearch-data-1,elasticsearch-ingest-0,elasticsearch-ingest-1
      ELASTICSEARCH_TOTAL_NODES:            4
      ELASTICSEARCH_CLUSTER_MASTER_HOSTS:   elasticsearch-master-0,elasticsearch-master-1
      ELASTICSEARCH_MINIMUM_MASTER_NODES:   2
      ELASTICSEARCH_ADVERTISED_HOSTNAME:    elasticsearch-coordinating-1
      ELASTICSEARCH_HEAP_SIZE:              1024m
      ELASTICSEARCH_ENABLE_SECURITY:        true
      ELASTICSEARCH_PASSWORD:               Elastic123
      ELASTICSEARCH_ENABLE_FIPS_MODE:       false
      ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      ELASTICSEARCH_ENABLE_REST_TLS:        true
      ELASTICSEARCH_TLS_USE_PEM:            true
      LOG_KB_TLS_ENABLE:                    true
    volumes:
       - ./certs/elasticsearch-coordinating.key:/opt/bitnami/elasticsearch/config/certs/tls.key
       - ./certs/elasticsearch-coordinating.crt:/opt/bitnami/elasticsearch/config/certs/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/elasticsearch/config/certs/ca.crt 
#       - data-elasticsearch-coordinating-1:/bitnami/elasticsearch/data
    networks:
      - app-tier
  elasticsearch-kibana:
    image: docker.io/bitnami/kibana:8.10.3-debian-11-r1      
    hostname: elasticsearch-kibana
    environment:
      BITNAMI_DEBUG:                               false
      KIBANA_PORT_NUMBER:                          5601
      KIBANA_ELASTICSEARCH_URL:                    https://elasticsearch-coordinating-0:9200
      KIBANA_ELASTICSEARCH_PORT_NUMBER:            9200
      KIBANA_FORCE_INITSCRIPTS:                    false
      KIBANA_SERVER_ENABLE_TLS:                    true
      KIBANA_SERVER_TLS_USE_PEM:                   true
      KIBANA_PASSWORD:                             "Elastic123"
      KIBANA_ELASTICSEARCH_PASSWORD:               "Elastic123"
      KIBANA_CREATE_USER:                          true
      KIBANA_ELASTICSEARCH_ENABLE_TLS:             true
      KIBANA_ELASTICSEARCH_TLS_USE_PEM:            true
      KIBANA_ELASTICSEARCH_TLS_VERIFICATION_MODE:  full
      LOG_KB_TLS_ENABLE:                           true
    volumes:
       - ./certs/elasticsearch-coordinating.key:/opt/bitnami/kibana/config/certs/elasticsearch/tls.key
       - ./certs/elasticsearch-coordinating.crt:/opt/bitnami/kibana/config/certs/elasticsearch/tls.crt
       - ./certs/rootCA.crt:/opt/bitnami/kibana/config/certs/elasticsearch/ca.crt
       - ./certs/kibana/rootCA.crt:/opt/bitnami/kibana/config/certs/server/ca.crt
       - ./certs/kibana/elasticsearch-kibana.key:/opt/bitnami/kibana/config/certs/server/tls.key
       - ./certs/kibana/elasticsearch-kibana.crt:/opt/bitnami/kibana/config/certs/server/tls.crt
       - elasticsearch-kibana:/bitnami/kibana
    networks:
      - app-tier

  nginx:
    image: docker.io/bitnami/nginx:1.21
    restart: unless-stopped
    user: root
    privileged: true
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./nginx/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.gnomen.conf:ro
      - ./certs/nginx/elk.yourapp.com.crt:/etc/elk.yourapp.com.crt
      - ./certs/nginx/elk.yourapp.com.key:/etc/elk.yourapp.com.key
    networks:
      - app-tier


volumes:
   data-elasticsearch-data-1:
   data-elasticsearch-data-0:
   data-elasticsearch-master-1:
   data-elasticsearch-master-0:
   elasticsearch-kibana:

